name: .NET

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Restore dependencies
      run: dotnet restore arianebus.sln

    - name: Extract config
      run: 7z x ${{github.workspace}}\src\localconfig.7z -p'${{secrets.localconfig}}' -o${{github.workspace}}\src\ArianeBus.Tests

    - name: Build
      run: dotnet build arianebus.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test arianebus.sln -c Release --no-build --verbosity normal

    - name: Pack ArianeBus
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}\src\ArianeBus\ArianeBus.csproj --output .

    - name: Push Nuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.nuget}} --skip-duplicate

